### ISSUE TITLE
Windows: Too many follow-up requests 21

### ISSUE THREAD

**Issue by cjaentsch** [fiskaly/fiskaly-kassensichv-client-java#10]
On windows (W10 64, OpenJDK 1.8.0_222-b10) we mostly get this Exception:
"Too many follow-up requests 21"

Most of the time the first transaction (startTransaction) still works, but the finishTransaction throws this error (not always but like 80% of the time).

![Bildschirmfoto 2019-09-12 um 18 35 40](https://user-images.githubusercontent.com/4006662/64803083-57ff5600-d58c-11e9-99c1-cdbc77212807.png)

**Comment by auxdevelopment** [comment]
Does this error still persist for you with the newly added changes?

Also, did that just occur on Windows machines or could you experience the same issue on a different platform as well?

**Comment by cjaentsch** [comment]
It feels like it happens less often right now, yet it still occurs in like 50% of the transactions. I haven't experienced this problem on MacOS.

**Comment by auxdevelopment** [comment]
I've tried to reproduce your error but failed unfortunately. This was the setup I've used:

```
OS: Windows 10
java version "1.8.0_101"
Java(TM) SE Runtime Environment (build 1.8.0_101-b13)
Java HotSpot(TM) 64-Bit Server VM (build 25.101-b13, mixed mode)
```

I've got some suspicions what could be causing the issue though:

- Are the environment variables `API_SECRET` and `API_KEY` set and valid? Otherwise the client will fail with the error you've received.
- Is it possible that the Windows machine sits behind a proxy that manipulates HTTP-Headers?

**Comment by cjaentsch** [comment]
When I retry the transaction it works (sometimes). So it's not a general problem, but in some occasions. Maybe I have to notice that we do all requests via a "persistent" Java app / server, so the app is started once and then handles all request to fiskaly. We also only create the GeneralSMA object once (per server app start) and use it for all following requests. It that the valid type of use or should we create an instance of the GeneralSMA for every request again?

Nevertheless the exception sometimes already occurs at the first transaction after the server start (so with a "fresh" GeneralSMA object).

I could also implement an automatic retry if the exception is thrown. Today I'm not in the office, but I will report and then we can see if we can narrow down the problem.

**Comment by cjaentsch** [comment]
Ok, so we tested it again. It happens randomly, but with 50% chance. I also tested to use a new instance of GeneralSMA for every request but that didn't work either, same behaviour.

Now we have implemented an automatic retry when this exception is thrown, so there is no impact anymore on our application. Nevertheless it's a weird thing.

**Comment by auxdevelopment** [comment]
That's especially weird because such a mechanism [already exists](https://github.com/fiskaly/fiskaly-kassensichv-client-java/blob/master/client/src/main/java/com/fiskaly/kassensichv/client/authentication/Authenticator.java). Are you sure you're using the latest version of the project?

You shouldn't need to create a new SMA instance for every request, one is sufficient.

**Comment by cjaentsch** [comment]
Yes, we are up to date on master branch of the client. Yet I don't think that this issue is related to the 401 status when credentials are expired. This works as expected. The "Too many follow-up requests" is thrown when there are valid credentials given but some other things happening.

**Comment by Greelings** [comment]
I have the same issue:
`2019-10-15 19:07:48.022 25771-26136/com.nymesis.alacarte W/System.err: java.net.ProtocolException: Too many follow-up requests: 21
2019-10-15 19:07:48.023 25771-26136/com.nymesis.alacarte W/System.err:     at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.kt:122)
2019-10-15 19:07:48.024 25771-26136/com.nymesis.alacarte W/System.err:     at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:112)
2019-10-15 19:07:48.024 25771-26136/com.nymesis.alacarte W/System.err:     at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:87)
2019-10-15 19:07:48.024 25771-26136/com.nymesis.alacarte W/System.err:     at com.fiskaly.kassensichv.client.interceptors.TransactionInterceptor.intercept(TransactionInterceptor.java:120)
2019-10-15 19:07:48.025 25771-26136/com.nymesis.alacarte W/System.err:     at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:112)
2019-10-15 19:07:48.025 25771-26136/com.nymesis.alacarte W/System.err:     at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:87)
2019-10-15 19:07:48.026 25771-26136/com.nymesis.alacarte W/System.err:     at com.fiskaly.kassensichv.client.interceptors.AuthenticationInterceptor.intercept(AuthenticationInterceptor.java:49)
2019-10-15 19:07:48.026 25771-26136/com.nymesis.alacarte W/System.err:     at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:112)
2019-10-15 19:07:48.026 25771-26136/com.nymesis.alacarte W/System.err:     at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:87)
2019-10-15 19:07:48.027 25771-26136/com.nymesis.alacarte W/System.err:     at com.fiskaly.kassensichv.client.interceptors.HeaderInterceptor.intercept(HeaderInterceptor.java:23)
2019-10-15 19:07:48.027 25771-26136/com.nymesis.alacarte W/System.err:     at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:112)
2019-10-15 19:07:48.027 25771-26136/com.nymesis.alacarte W/System.err:     at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:87)
2019-10-15 19:07:48.027 25771-26136/com.nymesis.alacarte W/System.err:     at okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.kt:184)
2019-10-15 19:07:48.028 25771-26136/com.nymesis.alacarte W/System.err:     at okhttp3.RealCall.execute(RealCall.kt:66)
2019-10-15 19:07:48.028 25771-26136/com.nymesis.alacarte W/System.err:     at com.nymesis.alacarte.partners.tax.Fiskaly._createTss(Fiskaly.java:81)`

**Comment by auxdevelopment** [comment]
Failed authentication will cause this behaviour. Did you verify that your credentials are valid for that example?

Regarding "it happens randomly": Does this means it works for some time but some requests randomly fail? If so, did you notice a particular group (e.g. targeting a specific resource) or type of requests failing or does that happen arbitrarily?

**Comment by Greelings** [comment]
I will try to collect more data the next time it happens.
