### ISSUE TITLE
Crash when creating a transaction on a Samsung S4 & S5

### ISSUE THREAD

**Issue by Greelings** [fiskaly/fiskaly-kassensichv-client-java#25]
It crashes at this line, when creating a transaction on a Samsung S4 or S5:            
`String response = Fiskaly.okHttpClient.newCall(request).execute().body().string();`

It works well on other devices.

Error log:
```
    java.lang.NoSuchMethodError: No static method join(Ljava/lang/CharSequence;Ljava/lang/Iterable;)Ljava/lang/String; in class Ljava/lang/String; or its super classes (declaration of 'java.lang.String' appears in /system/framework/core-libart.jar)
        at com.fiskaly.kassensichv.client.interceptors.TransactionInterceptor.rewriteRoute(TransactionInterceptor.java:59)
        at com.fiskaly.kassensichv.client.interceptors.TransactionInterceptor.createReroutedRequest(TransactionInterceptor.java:76)
        at com.fiskaly.kassensichv.client.interceptors.TransactionInterceptor.intercept(TransactionInterceptor.java:127)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:112)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:87)
        at com.fiskaly.kassensichv.client.interceptors.AuthenticationInterceptor.intercept(AuthenticationInterceptor.java:49)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:112)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:87)
        at com.fiskaly.kassensichv.client.interceptors.HeaderInterceptor.intercept(HeaderInterceptor.java:23)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:112)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:87)
        at okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.kt:184)
        at okhttp3.RealCall.execute(RealCall.kt:66)
```

**Comment by Greelings** [comment]
Same problem on a Samsung S5
Works well on a Samsung tab A 2016

**Comment by Greelings** [comment]
The issue only occurs when creating a transaction.
Creating a TSS or a CLIENT work well.

**Comment by prempador** [comment]
@Greelings Which Android Version (API Version) are you using on the S4 and S5. According to other issues I have seen String.join was added in Java 8 / Android API 26. What according to [https://en.wikipedia.org/wiki/Android_version_history#Android_8.0_Oreo_(API_26)](url) should be in Version 8.0 and higher.

**Comment by Greelings** [comment]
That's the problem. Our app is targeting devices >= API 21 (lollipop) Which represents 89.3% of the Android devices.
According to https://developer.android.com/about/dashboards, targeting devices >= API 26 will make our app compatible with only 38.7% of the Android devices. That's a serious problem for us.
Do you think possible to support devices from API 21?

**Comment by Greelings** [comment]
Here is how you can easily solve the problem:

> You can use TextUtils.join instead:
> 
> String result = TextUtils.join(", ", list);
> 
> (String.join was added in Java 8, which is why you can't use it in Android.)

Source: https://stackoverflow.com/a/33803041/5607457

**Comment by auxdevelopment** [comment]
Issue should be fixed by this [PR](https://github.com/fiskaly/fiskaly-kassensichv-client-java/pull/26).
