### ISSUE TITLE
Proguard rules

### ISSUE THREAD

**Issue by Greelings** [fiskaly/fiskaly-kassensichv-client-java#38]
I use the Android version. Everything works well. However after activating minifyEnabled and shrinkResources, it crashes when I make a request :
```
java.lang.AssertionError: impossible
        at java.lang.Enum$1.create(Enum.java:272)
        at java.lang.Enum$1.create(Enum.java:263)
        at libcore.util.BasicLruCache.get(BasicLruCache.java:58)
        at java.lang.Enum.getSharedConstants(Enum.java:289)
        at java.lang.Class.getEnumConstantsShared(Class.java:2417)
        at java.lang.Class.getEnumConstants(Class.java:2403)
        at com.fasterxml.jackson.databind.cfg.MapperConfig.g(SourceFile:99)
        at com.fasterxml.jackson.databind.cfg.MapperConfigBase.<clinit>(SourceFile:32)
        at com.fasterxml.jackson.databind.ObjectMapper.<init>(SourceFile:565)
        at com.fasterxml.jackson.databind.ObjectMapper.<init>(SourceFile:480)
```

So I added this rule to Proguard :
```
-keepclassmembers enum * {
    public static **[] values();
    public static ** valueOf(java.lang.String);
}
```

And now, I'm stuck with this error :
```
java.lang.UnsatisfiedLinkError: No implementation found for void d.a.a() (tried Java_d_a_a and Java_d_a_a__)
        at d.a.a(Native Method)
        at d.a.<clinit>(SourceFile:38)
        at d.a.b(SourceFile:50)
        at c.b.a.b.b.<clinit>(SourceFile:11)
        at c.b.a.b.b.a(Native Method)
        at c.b.a.b.a.a(SourceFile:6)
        at c.b.a.a.c.c.b(SourceFile:49)
        at c.b.a.a.c.c.intercept(SourceFile:147)
        at okhttp3.internal.http.RealInterceptorChain.proceed(SourceFile:112)
        at okhttp3.internal.http.RealInterceptorChain.proceed(SourceFile:87)
        at c.b.a.a.c.a.intercept(SourceFile:49)
        at okhttp3.internal.http.RealInterceptorChain.proceed(SourceFile:112)
        at okhttp3.internal.http.RealInterceptorChain.proceed(SourceFile:87)
        at c.b.a.a.c.b.intercept(SourceFile:23)
        at okhttp3.internal.http.RealInterceptorChain.proceed(SourceFile:112)
        at okhttp3.internal.http.RealInterceptorChain.proceed(SourceFile:87)
        at okhttp3.RealCall.getResponseWithInterceptorChain(SourceFile:184)
        at okhttp3.RealCall.execute(SourceFile:66)
```

The problem comes from the Proguard rules for Jackson and OkHttp.

**Comment by Greelings** [comment]
After adding:
`-keep class com.fiskaly.kassensichv.** { *; }`

I learned more info about the problem:
```
    java.lang.UnsatisfiedLinkError: No implementation found for void d.a.a() (tried Java_d_a_a and Java_d_a_a__)
        at d.a.a(Native Method)
        at d.a.<clinit>(SourceFile:38)
        at d.a.b(SourceFile:50)
        **at com.fiskaly.kassensichv.sma.Sma.<clinit>(SourceFile:11)
        at com.fiskaly.kassensichv.sma.Sma.invoke(Native Method)
        at com.fiskaly.kassensichv.sma.AndroidSma.invoke(SourceFile:6)
        at com.fiskaly.kassensichv.client.interceptors.TransactionInterceptor.signTransaction(SourceFile:49)
        at com.fiskaly.kassensichv.client.interceptors.TransactionInterceptor.intercept(SourceFile:147)**
        at okhttp3.E.d.g.a(SourceFile:112)
        at okhttp3.E.d.g.a(SourceFile:87)
        at com.fiskaly.kassensichv.client.interceptors.AuthenticationInterceptor.intercept(SourceFile:49)
        at okhttp3.E.d.g.a(SourceFile:112)
        at okhttp3.E.d.g.a(SourceFile:87)
        at com.fiskaly.kassensichv.client.interceptors.HeaderInterceptor.intercept(SourceFile:23)
        at okhttp3.E.d.g.a(SourceFile:112)
        at okhttp3.E.d.g.a(SourceFile:87)
        at okhttp3.x.c(SourceFile:184)
        at okhttp3.x.a(SourceFile:66)
```

**Comment by Greelings** [comment]
It comes from this class:
```
package com.fiskaly.kassensichv.sma;

import go.Seq;

public abstract class Sma {
    private Sma() {
    }

    public static void touch() {
    }

    private static native void _init();

    public static native String invoke(String var0);

    static {
        Seq.touch();
        _init();
    }
}
```

**Comment by Greelings** [comment]
From this line more precisely:
**Seq.touch();**
What's the **go.Seq** library?

**Comment by Greelings** [comment]
Problem fixed. Here are the Proguard rules:
```
# Fiskaly
-keepclassmembers enum * {
    public static **[] values();
    public static ** valueOf(java.lang.String);
}
-keep class com.fiskaly.kassensichv.sma.** { *; }
-keep class go.** { *; }
```
